### ISSUE TITLE
"Server Not Found" error not reloading

### ISSUE THREAD

**Issue by Morpheus0x** [ryhaberecht/MAKE-A-MERRY-TRY-AGAIN#3]
Below an image of two sites with different errors. I have no idea why they are different, my only guess would be because the first site is displayed and the second is a hidden tab. I have searched the error codes at https://developer.mozilla.org/en-US/docs/Mozilla/Errors but have not found a matching error code I could add to the background.js script...
![firefox_connection](https://user-images.githubusercontent.com/22265595/88512489-f51d7e80-cfe6-11ea-9e14-e462e1ed6422.png)

**Comment by Morpheus0x** [comment]
Ok I think I have found the problem. If I reload the "Server not found" site once, the extension kicks in and reloads the site. I think the problem is that the extension only starts after the first site tries to load... I have no idea on how to solve this, this may be impossible since the time when extensions are loaded is determined by firefox itself...
Also the difference in errors is because the first site has a domain name and the second is an ip address...

**Comment by ryhaberecht** [comment]
Hi.

A NXDOMAIN from your DNS server results in the NS_ERROR_UNKNOWN_HOST Error.
I just tested with a bogus URL and got this from the log:

> [MMTA] reloading... background.js:97:13
> [MMTA] finished reloading background.js:120:13
> [MMTA] failed: http://www.lsjldfjoieljflm.com/ -> NS_ERROR_UNKNOWN_HOST background.js:77:21
> [MMTA] timeout = 5

I could also see the tab trying to reload every 5 seconds.

You can access the log of an extension by entering the Add-on Manager, click on the gear, Debug Add-ons and next to MMTA hit Inspect. Maybe you can try again and check the log to see what MMTA is doing.

**Comment by ryhaberecht** [comment]
not reproducible
